site_name: Demo Site
site_description: Demo Site description
site_author: YOUR-NAME
theme:
  name: 'material'
markdown_extensions:
  - toc
  - extra
  - codehilite
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.tabbed
nav:
    - "Home": "index.md"
